[package]
name = "arbitrager_uni_sushi_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0.14"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"

[dev-dependencies]
ethers = "2.0.14"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
